### ISSUE TITLE
Protocol 2.5 - Split the flashloan fee in liquidity providers fee and protocol fee

### ISSUE THREAD

**Issue by The-3D** [aave/protocol-v2#105]
Currently it's not possible to split between protocol and liquidity providers fee on flashloans. Add the possibility to split between flashloan fee and protocol fee, and increase the fee precision by two more decimals (from 1e5 to 1e7). The amount for the protocol should be passed to ```updateState()``` and added to the treasury in the ```_mintToTreasury()``` function.

**Comment by dhadrien** [comment]
- test multiple asset
- test protocol premium 
- add the commit merging both authorized and aunothorized flashloan tests
