### ISSUE TITLE
Protocol 2.5 - Add whitelisting capabilities for flashloans

### ISSUE THREAD

**Issue by The-3D** [aave/protocol-v2#106]
Add the possibility of allowing free flashloans for whitelisted entities. This requires a mapping in LendingPoolStorage that keeps track of whitelisted addresses.

**Comment by yzhou61** [comment]
Hi, just curious, what is required to be whitelisted?

**Comment by The-3D** [comment]
Hello, a governance vote will be needed to be whitelisted. Otherwise anyone can use by paying a fee
