### ISSUE TITLE
Depositing and Borrowing APR

### ISSUE THREAD

**Issue by jakemathai5** [aave/protocol-v2#118]
Which contract/function/formula gives the current deposit and borrow APR rewards rate for a given asset? 

I'm referring to the small number under the APY in the app representing market participation rewards. I can see in the docs how to get the deposit and borrow APY rates via `LendingPool.getReserveData()` but not the APR rewards/incentives rate.

**Comment by shivgupt** [comment]
APR rewards/incentives rate are part of of liquidity mining.

Refer to `getAssetData()` here ➡️ https://docs.aave.com/developers/guides/liquidity-mining#getassetdata

**Comment by jakemathai5** [comment]
@shivgupt Ah thank you, I must've glossed over that. I can't seem to find the full signature for that function on the AAVEIncentivesController contract - I am generating the contract ABI from my own interface contract so I need the full signature. Can you tell me what might be wrong with this?
`function getAssetData(address asset) external view returns (uint256[] memory);`

**Comment by shivgupt** [comment]
Docs have link to polygon market contracts too. Check [this](https://github.com/aave/aave-stake-v2/tree/feat/incentives/mumbai-config/contracts/stake) branch.

But `getAssetData()` is not implemented in polygon contracts. So, on polygon you will have to get info via public mapping `assets`
