### ISSUE TITLE
getAddress('0x1') get 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by dengxp** [aave/protocol-v2#123]
const providerContract = new web3.eth.Contract(
        addressProviderABI,
        providerAddress
      );

      providerContract.methods.getAddress("0x1").call()
      .then(address => {
        console.log("protocolDataProviderAddress: ", address);
      })
      .catch(err=> {
        console.error("getAddress Error: ", err);
      });

protocolDataProviderAddress:  0x0000000000000000000000000000000000000000

**Comment by nkolchakov** [comment]
Got the same issue using Brownie

**Comment by shivgupt** [comment]
Try `providerContract.methods.getAddress("0x0100000000000000000000000000000000000000000000000000000000000000").call()` instead

**Comment by ScienceBlocker** [comment]
Got the same issue using Brownie.Me too~~~
Does some one to help us out please.
Always return 0x0000000000000000000000000000000000000000

**Comment by risinek** [comment]
I see this kind of unintuitive because it expects different value than what documentation says.
In documentation
> Each market has a separate Protocol Data Provider. To get the address for a particular market, call [getAddress()](https://github.com/developers/v/2.0/the-core-protocol/addresses-provider#getaddress) using the value 0x1.

`0x1` would rather equal to `0x0000000000000000000000000000000000000000000000000000000000000001` padded 32 bytes right? Or am I missing something?
