### ISSUE TITLE
[question] The parameters in Interest Rate Model

### ISSUE THREAD

**Issue by master-davidlee** [aave/protocol-v2#124]
Hi, I read the doc of interest rate model doc and met some confusion. 
- There are many const parameters like Uoptimal, Base, Slope 1, Slope 2. How to sure their value and how to adapt them if something changes. Who decides the old parameters and who decides the new parameters. The doc link is below 
https://docs.aave.com/risk/liquidity-risk/borrow-interest-rate#model-parameters

- the loan to value (LTV) and liquidation threshold also confuses me, if you can tell me that I will appreciate it. 
https://docs.aave.com/risk/asset-risk/risk-parameters#loan-to-value

**Comment by ABertoG** [comment]
Hi @master-davidlee 

The risk parameters have been calibrated based on historical market data and user behaviour on Aave

For smooth liquidations you need enough market liquidity to liquidity without too much slippage so its based on volatility and liquidity (both in terms of volume and sources). The LTV is mostly calibrated based on the volatility of the underlying asset as well as the Liquidation Threshold.

More details on the calibration from risks to parameters here https://docs.aave.com/risk/asset-risk/risk-parameters#from-risks-to-risk-parameters


The interest rate model is calibrated in a similar way. The liquidity of different reserve is constantly monitored to ensure there is sufficient liquidity for the protocol to function well. Last year V1 allowed to test the interest rate model, a few tweaks were made to the make the model resilient and avoid prolonged lack of liquidity.  The larger the reserve the less volatile allowing more aggressive parameters. In additional a market analysis was run to understand market borrow rates. This lead to 2 major interest rate models:

- Volatile cryptocurrencies are predominantly collaterals, spare liquidity is crucial in case liquidations occur, requiring the underlying asset. For this reason the Optimal Utilisation is generally around 45%
Volatile Asset Model U=45% S0=0% S1=7% S2=300%
Some parameters where adapted following high demand on Aave

- Stablecoins are predominantly borrowing assets, spare liquidity is important for depositors to withdraw
Safe & Large Stablecoin Model U= 90% S0= 0% S1=4% S2=100%
Smaller Stablecoins U= 80% S0=0% S1=4% S2 = 75 to 100%

These calibrations have been reviewed by Gauntlet who deemed them appropriate https://gauntlet.network/reports/aave

These parameters are submitted with asset listing Aave Improvement Proposals (AIP) with the need to be approved by governance. If risks change and the parameters need to evolve, this would also require an AIP and governance vote.

Feel free to join the Aave Discord which is the best place to ask questions and exchange in a more interactive way https://discord.gg/nvB8aunx

**Comment by master-davidlee** [comment]
Thank you so much,  your answer solves a lot of questions.
