### ISSUE TITLE
a problem of LendingPool.sol 's withdraw function

### ISSUE THREAD

**Issue by wanggeng01041454** [aave/protocol-v2#147]
if the second argument of function `withdraw` is `type(uint256).max`，then, we get
`amountToWithdraw = IAToken(aToken).balanceOf(msg.sender)`;
it equals to:
`amountToWithdraw =_balances[msg.sender].rayMul(_pool.getReserveNormalizedIncome(_underlyingAsset)`
`amountToWithdraw  > _balances[msg.sender]` must be TRUE;

BUT, when it call `IAToken(aToken).burn(...)`,
it's implementation is like this:
```
    uint256 oldAccountBalance = _balances[account];
    _balances[account] = oldAccountBalance.sub(amountToWithdraw , 'ERC20: burn amount exceeds balance');
````
__the `sub` action will exceeds__

**Comment by The-3D** [comment]
The burn() action divides the amount passed by the current index first. The balance is stored in "scaled" format (actual balance/index). Here is the code

```
 function burn(
    address user,
    address receiverOfUnderlying,
    uint256 amount,
    uint256 index
  ) external override onlyLendingPool {
    uint256 amountScaled = amount.rayDiv(index);
    require(amountScaled != 0, Errors.CT_INVALID_BURN_AMOUNT);
    _burn(user, amountScaled);

    IERC20(_underlyingAsset).safeTransfer(receiverOfUnderlying, amount);

    emit Transfer(user, address(0), amount);
    emit Burn(user, receiverOfUnderlying, amount, index);
  }
  ```
so before calling _burn() the amount is scaled, which guarantees the sub() will not exceed.
