### ISSUE TITLE
LendingPool.getAddressesProvider returns an empty array, not a addressesProvider instance

### ISSUE THREAD

**Issue by liran319** [aave/protocol-v2#176]
Here is my strps:
```
const providerInstance = new ethers.Contract(Address_LendingPoolAddressesProvider, ABI_LendingPoolAddressesProvider, this.signer)

const providerAddress = await providerInstance.callStatic.getLendingPool()
const lendingPoolInstance = new ethers.Contract(providerAddress, ABI_LendingPool, this.signer)
const _addressesProvider = await lendingPoolInstance.callStatic.getAddressesProvider()
console.log('lendingPool.getAddressesProvider', _addressesProvider)
```
console result: 
```
lendingPool.getAddressesProvider []
```

Why did it return an empty array, not a addressesProvider instance?
As the doc says that it should `Returns the addresses provider`
![image](https://user-images.githubusercontent.com/4019372/124414081-8a42fe80-dd84-11eb-9adc-8b32db90d5db.png)

**Comment by The-3D** [comment]
a quick check through etherscan shows that the call indeed returns a single address, which is the address of the addresses provider. Can you validate your ABI against the etherscan ABI? 

![image](https://user-images.githubusercontent.com/37953689/124502034-f17fa380-ddc2-11eb-80ab-7d9499213e1f.png)

**Comment by liran319** [comment]
> a quick check through etherscan shows that the call indeed returns a single address, which is the address of the addresses provider. Can you validate your ABI against the etherscan ABI?
> 
> ![image](https://user-images.githubusercontent.com/37953689/124502034-f17fa380-ddc2-11eb-80ab-7d9499213e1f.png)

I see, that means to return a contract address. 
I thought it would return a addressesProvider instance.
Thanks!

**Comment by The-3D** [comment]
i see the confusion - will ask to update the documentation. closing
