### ISSUE TITLE
Cannot find module '../types' in test

### ISSUE THREAD

**Issue by MuMiMaNz** [aave/protocol-v2#2]
Hello Aave team,
I want to run a test and got this error

`Error: Cannot find module '../types'
Require stack:
- /src/helpers/contracts-getters.ts
- /src/helpers/contracts-helpers.ts
- /src/tasks/misc/initialize-tokens.ts
- /src/hardhat.config.ts
- /src/node_modules/hardhat/internal/core/config/config-loading.js
- /src/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/src/helpers/contracts-getters.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/src/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/src/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/src/helpers/contracts-getters.ts',
    '/src/helpers/contracts-helpers.ts',
    '/src/tasks/misc/initialize-tokens.ts',
    '/src/hardhat.config.ts',
    '/src/node_modules/hardhat/internal/core/config/config-loading.js',
    '/src/node_modules/hardhat/internal/cli/cli.js'
  ]
}
`

and I look at in helper folder, it's missing lots of things, maybe you forgot the "types" folder ?

**Comment by Skyge** [comment]
lending Kovan(12-10):
-----------------------------------------------
usdt : 0x128c10cAD3780a541325A2f4B9E449114aD11D6b;
usdx : 0xC251A1Da17bE0Cea838f087051D0Cbf683B53054;
InterestModel contract is:  0x6c27FFF7517f3459EF06D02fe97B93F0BDe65640
Controller contract is:     0x5c1DeEb733ca049B50b7c4531fcDb14f062e7d0A
lending USDT contract is:   0xC9485CDA692E18aF8C2EAcB2305DE7E2bDDbE4DA
lending USDx contract is:   0x83Ff771e87065B2468a5951e4b45Ce1245ea678C
Price oracle contract is:   0x7B21319EcB55d7e0e6876Ce562171C6628ddd26c

faucet方法为allocateTo(to,amount);

:bug: Fix <deploy.js>: Fix token address when feeding.

**Comment by PabiGamito** [comment]
You need to compile the contracts and have typechain run. Typechain will generate everything you need in the types folder.

Set the environment variable `SKIP_LOAD` to `true` (`export SKIP_LOAD="true"`) then run `npx hardhat compile`.

**Comment by nkrsic** [comment]
This is a really weird and silly big in VSCode auto-complete, I just experienced it exactly. When you type the it() clauses for testing, autocomplete fights you to insert isTypedArray() from util/types, and it also adds the import. The import added by VSCode code-completion / syntax help is what is causing this. Check the top of your testing file.
