### ISSUE TITLE
Unnecessary check on repay vaildation

### ISSUE THREAD

**Issue by vminkov** [aave/protocol-v2#221]
It looks like this line is some leftover from v1 when there were contract vaults like `CreditDelegationVault`

https://github.com/aave/protocol-v2/blob/ccb43f026f4ef25ba338073d02dec5c58123da32/contracts/protocol/libraries/logic/ValidationLogic.sol#L246

It is essentially an obsolete check that can be removed

**Comment by The-3D** [comment]
hello - this check is actually still valid as it handles a potential frontrunning attack when repaying on behalf. The attack would be the following:
1) repayer approves uint256.max for the repayment
2) repayer sends a repayment on behalf tx with amount = uint256.max
3) borrower frontruns this transaction to borrow more than the initial amount
4) repayer ends up paying more than expected

This check prevents this scenario from happening.
