### ISSUE TITLE
What is the best way to integrate my smart contract with `LendingPool` & `LendingPoolProvider` ?

### ISSUE THREAD

**Issue by akcgjc007** [aave/protocol-v2#49]
I am creating a smart contract that has to use the *AAVE* lending pool feature. And hence, I need to call `LendingPool` from my solidity-based smart contract. 

My plan is:
 - writing my smart contract in the `contracts` directory of `protocol-v2`
 - import `LendingPool.sol` & `LendingPoolProvider.sol` in my contract
 - Use the `redeem()`... & other stuff
 - Compile & Deploy

**Is there any other simpler way of doing this?**

@mrdavey

**Comment by kyzia551** [comment]
Hi @akcgjc007!
The simplest way of interacting with the LendingPool is just to import ILendingPool interface from our npm package. You don't need the whole contract

Please check an example here: https://github.com/aave/protocol-v2#getting-started
