### ISSUE TITLE
UNDERLYING_ASSET_ADDRESS missing in IAToken

### ISSUE THREAD

**Issue by PierrickGT** [aave/protocol-v2#50]
**Problem**

It is stated in the doc that we can retrieve the underlying asset of a aToken by doing `aToken.UNDERLYING_ASSET_ADDRESS()` => https://docs.aave.com/developers/the-core-protocol/atokens#underlying_asset_address
Sadly, this method isn't present in the interface so if we just import the interface in our Solidity code by doing `import "@aave/protocol-v2/contracts/interfaces/IAToken.sol";` we won't have access to `UNDERLYING_ASSET_ADDRESS` function.
We can of course declare our own interface and extend the original interface but it would be best to only have to import the original interface.

**Solution**

Add `function UNDERLYING_ASSET_ADDRESS() external view returns (address);` to https://github.com/aave/protocol-v2/blob/master/contracts/interfaces/IAToken.sol

**Comment by The-3D** [comment]
Great call! thanks!

**Comment by The-3D** [comment]
If you don't mind creating a PR for it, i would gladly review and merge

**Comment by PierrickGT** [comment]
@The-3D here is the PR: https://github.com/aave/protocol-v2/pull/51
