### ISSUE TITLE
Protocol 2.5 - Integration of depositWithPermit, repayWithPermit

### ISSUE THREAD

**Issue by The-3D** [aave/protocol-v2#63]
For protocol 2.5, there needs to be the possibility of depositing and repaying using the permit function, to avoid the approve/transfer pattern which brings additional gas cost for the users.

Currently the EIP 2612 is supported by the following tokens:

- DAI
- USDC
- AAVE
- UNI

**Comment by dhadrien** [comment]
Adding withdrawWithPermit, since ATokens implement 2612 too

**Comment by The-3D** [comment]
merged #65
