### ISSUE TITLE
Kovan Deployment - Provider exception

### ISSUE THREAD

**Issue by PraneshASP** [aave/protocol-v2#67]
Hi,
Everything is working fine. But the issue is, during full migration on kovan network, the ```authorizeWETHGateway(gateWay, lendingPoolAddress);``` method is throwing exception on the Initialize Lending Pool (last) step.

The error message is : ```ProviderError: The execution failed due to an exception.```

Please look into this. Thanks in advance.

**Comment by miguelmtzinf** [comment]
Hi @PraneshASP 
Are you still having problems?
Is the issue #62 the same as this one?

**Comment by PraneshASP** [comment]
Hi @miguelmtzinf 

 > Are you still having problems? 

No, I have fixed the issues. I forgot to close this issue. Thanks for pointing out!

> Is the issue #62 the same as this one?

No, both are different. I'll close it as well.
